# Generated by Django 5.2.17 on 2026-10-02 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_reconcile_paid_orders'),
        ('flowza_bot_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botorderreceipt',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.order'),
        ),
    ]
