# Generated by Django 5.2.17 on 2026-10-02 06:47

import django.core.validators
from decimal import Decimal
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('source', models.CharField(choices=[('BOT', 'Bot'), ('MANUAL', 'Manual'), ('TRANSFER', 'Transfer'), ('OTHER', 'Other')], default='MANUAL', max_length=10)),
                ('external_id', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=150)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('districts', models.JSONField(default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('internal_rating', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3)),
                ('completed_orders_count', models.PositiveIntegerField(default=0, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PAID', 'Paid'), ('CANCELLED_CLIENT', 'Cancelled Client'), ('CANCELLED_MASTER', 'Cancelled Master'), ('TRANSFERRED', 'Transferred'), ('REFUNDED', 'Refunded')], default='NEW', max_length=20)),
                ('source', models.CharField(choices=[('BOT', 'Bot'), ('MANUAL', 'Manual'), ('TRANSFER', 'Transfer'), ('OTHER', 'Other')], default='MANUAL', max_length=10)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.client')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='crm.masterprofile')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.specialization')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='crm.order')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterSpecialization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='crm.masterprofile')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.specialization')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='OFFERED', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='crm.masterprofile')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='crm.order')),
                ('to_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='crm.masterprofile')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('dedup_key', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='crm_notific_user_id_d94ba6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('type', models.CharField(choices=[('PREPAYMENT', 'Prepayment'), ('FULL', 'Full'), ('REFUND', 'Refund')], max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='PAID', max_length=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='crm.order')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_positive')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='crm.masterprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='crm.order')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='review_score_range')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('ORDER', 'Order'), ('MANUAL', 'Manual'), ('UNAVAILABLE', 'Unavailable')], default='MANUAL', max_length=15)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='crm.masterprofile')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_block', to='crm.order')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['master', 'start_at', 'end_at'], name='crm_schedul_master__917cb5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_at__lt', models.F('end_at'))), name='block_valid_interval'), models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('type', 'ORDER')), models.Q(models.Q(('type', 'ORDER'), _negated=True), ('order__isnull', True)), _connector='OR'), name='block_order_type')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['master', 'status', 'start_at'], name='crm_order_master__98ba1c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', '-created_at'], name='crm_order_client__08bd36_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('start_at__lt', models.F('end_at'))), name='order_valid_interval'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('final_price__gte', 0), ('final_price__isnull', True), _connector='OR'), name='order_nonnegative_final'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_price__gte', 0), ('estimated_price__isnull', True), _connector='OR'), name='order_nonnegative_estimate'),
        ),
        migrations.AddConstraint(
            model_name='masterspecialization',
            constraint=models.UniqueConstraint(fields=('master', 'specialization'), name='unique_master_skill'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['to_master', 'status', '-offered_at'], name='crm_transfe_to_mast_207502_idx'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_master', models.F('to_master')), _negated=True), name='transfer_different_masters'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OFFERED')), fields=('order', 'to_master'), name='unique_active_offer'),
        ),
    ]
