# Generated by Django 5.2.17 on 2026-10-02 19:00

import crm.working_hours
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='timezone',
            field=models.CharField(default='Asia/Almaty', max_length=100, validators=[crm.working_hours.validate_timezone]),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='working_hours',
            field=models.JSONField(default=crm.working_hours.default_working_hours, validators=[crm.working_hours.validate_working_hours]),
        ),
    ]
